package org.omg.IOP;


/**
* org/omg/IOP/ENCODING_CDR_ENCAPS.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from c:/re/workspace/8-2-build-windows-amd64-cygwin/jdk8u181/11358/corba/src/share/classes/org/omg/PortableInterceptor/IOP.idl
* Saturday, July 7, 2018 4:03:12 AM PDT
*/

public interface ENCODING_CDR_ENCAPS
{

  /**
   * The CDR Encapsulation encoding.
   * @see CodecFactory
   */
  public static final short value = (short)(0);
}
